{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "restaurant-system.apiGateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
  - port: {{ .Values.apiGateway.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if .Values.apiGateway.service.nodePort }}
    nodePort: {{ .Values.apiGateway.service.nodePort }}
    {{- end }}
  selector:
    app: {{ .Values.apiGateway.name }}
{{- end }}
