{{- if .Values.receiptService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.receiptService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.receiptService.name }}
spec:
  type: {{ .Values.receiptService.service.type }}
  ports:
  - port: {{ .Values.receiptService.service.port }}
    targetPort: {{ .Values.receiptService.service.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.receiptService.name }}
{{- end }}
